# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
  kind: "Deployment"
  apiVersion: "extensions/v1beta1"
  metadata: 
    name: "container-broker"
  spec: 
    replicas: 1
    selector: 
      matchLabels: 
        id: "container-broker"
    template: 
      metadata: 
        labels: 
          id: "container-broker"
      spec: 
        containers: 
          - 
            name: "container-broker"
            image: "tap-container-broker"
            ports: 
              - 
                containerPort: 80
                protocol: "TCP"
            env: 
              - 
                name: "CONTAINER_BROKER_PORT"
                valueFrom: 
                  configMapKeyRef: 
                    name: "container-broker-credentials"
                    key: "container-broker-port"
              - 
                name: "CONTAINER_BROKER_USER"
                valueFrom: 
                  configMapKeyRef: 
                    name: "container-broker-credentials"
                    key: "container-broker-user"
              - 
                name: "CONTAINER_BROKER_PASS"
                valueFrom: 
                  configMapKeyRef: 
                    name: "container-broker-credentials"
                    key: "container-broker-pass"
              - 
                name: "CONTAINER_BROKER_SSL_KEY_FILE_LOCATION"
                valueFrom: 
                  configMapKeyRef: 
                    name: "container-broker-credentials"
                    key: "container-broker-ssl-key-file-location"
              - 
                name: "CONTAINER_BROKER_SSL_CERT_FILE_LOCATION"
                valueFrom: 
                  configMapKeyRef: 
                    name: "container-broker-credentials"
                    key: "container-broker-ssl-cert-file-location"
              - 
                name: "TEMPLATE_REPOSITORY_KUBERNETES_SERVICE_NAME"
                valueFrom: 
                  configMapKeyRef: 
                    name: "container-broker-credentials"
                    key: "template-repository-kubernetes-service-name"
              - 
                name: "TEMPLATE_REPOSITORY_USER"
                valueFrom: 
                  configMapKeyRef: 
                    name: "container-broker-credentials"
                    key: "template-repository-user"
              - 
                name: "TEMPLATE_REPOSITORY_PASS"
                valueFrom: 
                  configMapKeyRef: 
                    name: "container-broker-credentials"
                    key: "template-repository-pass"
              - 
                name: "TEMPLATE_REPOSITORY_SSL_CERT_FILE_LOCATION"
                valueFrom: 
                  configMapKeyRef: 
                    name: "container-broker-credentials"
                    key: "template-repository-ssl-cert-file-location"
              - 
                name: "TEMPLATE_REPOSITORY_SSL_KEY_FILE_LOCATION"
                valueFrom: 
                  configMapKeyRef: 
                    name: "container-broker-credentials"
                    key: "template-repository-ssl-key-file-location"
              - 
                name: "TEMPLATE_REPOSITORY_SSL_CA_FILE_LOCATION"
                valueFrom: 
                  configMapKeyRef: 
                    name: "container-broker-credentials"
                    key: "template-repository-ssl-ca-file-location"
              - 
                name: "CATALOG_KUBERNETES_SERVICE_NAME"
                valueFrom: 
                  configMapKeyRef: 
                    name: "container-broker-credentials"
                    key: "catalog-kubernetes-service-name"
              - 
                name: "CATALOG_USER"
                valueFrom: 
                  configMapKeyRef: 
                    name: "container-broker-credentials"
                    key: "catalog-user"
              - 
                name: "CATALOG_PASS"
                valueFrom: 
                  configMapKeyRef: 
                    name: "container-broker-credentials"
                    key: "catalog-pass"
              - 
                name: "CATALOG_SSL_CERT_FILE_LOCATION"
                valueFrom: 
                  configMapKeyRef: 
                    name: "container-broker-credentials"
                    key: "catalog-ssl-cert-file-location"
              - 
                name: "CATALOG_SSL_KEY_FILE_LOCATION"
                valueFrom: 
                  configMapKeyRef: 
                    name: "container-broker-credentials"
                    key: "catalog-ssl-key-file-location"
              - 
                name: "CATALOG_SSL_CA_FILE_LOCATION"
                valueFrom: 
                  configMapKeyRef: 
                    name: "container-broker-credentials"
                    key: "catalog-ssl-ca-file-location"
              - 
                name: "INSECURE_SKIP_VERIFY"
                valueFrom: 
                  configMapKeyRef: 
                    name: "container-broker-credentials"
                    key: "insecure-skip-verify"
              - 
                name: "BROKER_LOG_LEVEL"
                valueFrom: 
                  configMapKeyRef: 
                    name: "container-broker-credentials"
                    key: "broker-log-level"
              - 
                name: "CHECK_JOB_INTERVAL_SEC"
                valueFrom: 
                  configMapKeyRef: 
                    name: "container-broker-credentials"
                    key: "check-job-interval-sec"
            imagePullPolicy: "IfNotPresent"
        restartPolicy: "Always"
        dnsPolicy: "ClusterFirst"